### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by bit97** [bit97/onthisday#1]
**To be done:**

- [ ] Add tests
- [ ] Cache downloaded pages
- [x] Better division of event sources
- [ ] Add other event sources
- [x] Handle different languages
